### ISSUE TITLE
missing .meta files

### ISSUE THREAD

**Issue by brogan89** [GilpStudio/unity-internal-icon-browser#1]
Glad I found this. Made it much easier to find what I was looking for. But there are missing meta files Unity can generate because the folder is immutable when loaded from git repo.

You can change `Documentation` folder to `Documentation~` and Unity will ignore that one. 
but the `LICENSE.meta`, you will need to push that one. 

I was going to make a PR but its a small thing. 

Thanks for this 😄

**Comment by garrafote** [comment]
Hi, I'm glad you found the tool useful, and thank you for pointing out this issue.

And yeah the repo is so tiny that it almost felt like I should bump the minor version after fixing this 😂
